export const SpecialistData = [
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
  { Photo: "", Name: "Hello", Profession: "Tharapiest" },
];
